# Generated by Django 2.0.1 on 2018-01-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr104',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('appear_data', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('job_descript', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('salary_high', models.IntegerField(blank=True, null=True)),
                ('salary_low', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('big_add', models.TextField(blank=True, null=True)),
                ('small_add', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr104',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipeen',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('tele', models.TextField(blank=True, null=True)),
                ('averagecost', models.TextField(blank=True, null=True)),
                ('viewcount', models.IntegerField(blank=True, null=True)),
                ('ncomment', models.IntegerField(blank=True, db_column='Ncomment', null=True)),
                ('bigstyle', models.TextField(blank=True, null=True)),
                ('smallstyle', models.TextField(blank=True, null=True)),
                ('bigadd', models.TextField(blank=True, null=True)),
                ('smalladd', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipeen',
                'managed': False,
            },
        ),
    ]
